### ISSUE TITLE
关于物品栏关闭时的输入冲突问题(BUG)

### ISSUE THREAD

**Issue by Hambaka** [mrjesen/ImBlockerFabric#1]
**描述bug:**
1. 首先将输入法切换为中文输入法。
2. 在生存模式中，按"E"打开物品栏是没问题的，但是如果此时物品栏开启了合成书功能，想要按"E"关闭物品栏时会跳出输入法。只能按"ESC"强行关闭物品栏。可能由合成书的合成配方搜索栏导致，即便当前没有在搜索栏输入框输入文字，也会认为此时是输入文字状态。
3. 同样，如果处于创造模式，按"E"打开物品栏也是没问题的，但是想要按"E"关闭物品时也会跳出输入法。只能按"ESC"强行关闭物品栏。可能由创造模式物品栏的搜索标签页的搜索栏导致，即便当前没有在搜索栏输入框输入文字，也会认为此时是输入文字状态。
4. 只有处于生存模式且物品栏不开启合成书功能时，可按“E”打开也可以按"E"关闭，不会跳出输入法。

**bug重现方式:**
大体流程同上。

**预期结果:**
上述两种情况下，按"E"正常关闭物品栏，不会跳出输入法。

**截图:**
无

**运行环境:**
 - 操作系统: Windows 10 专业版 Version 1909
 - 输入法: 中文(简体，中国)，微软拼音；英语(美国)，美式键盘
 - Minecraft: 1.16.1
 - Fabric: 0.9.0+build.204
 - Mod版本: 1.0.2
 - 同时运行的其它Mod:  fabric-api-0.15.0+build.379-1.16.1, modmenu-1.14.5+build.30
 - 分支: master

**额外说明:**
1. 生存模式中，在物品栏打开的情况下（此时为开启合成书的物品栏），即便按合成书图标将物品栏调整为无合成书的物品栏，按"E"也无法直接关闭，会跳出输入法。"ESC"强制关闭后，再次开启物品栏，一切行为如同上述第4条，恢复正常。

**Comment by mrjesen** [comment]
收到，我尝试复现了一下，确实出现了这种情况，我研究一下如何修复。

**Comment by mrjesen** [comment]
看一下新版本，我已经修复了
