### ISSUE TITLE
[BUG] 与optifabric或optifine冲突

### ISSUE THREAD

**Issue by Polonium84** [mrjesen/ImBlockerFabric#12]
**Describe the bug**
与optifabric或optifine冲突

**Client Software**
HMCL (MC: 1.16.4)

**mods**
 - optifabric-1.8.10
 - OptiFine_1.16.4_HD_U_G5

**Screenshots**
![image](https://user-images.githubusercontent.com/63310093/101044383-3ee02c00-35ba-11eb-8eb6-2a45a618edde.png)

**Environment(please complete the following information):**
 - OS: [e.g. Windows 10 1903 (18362.175)]
 - JRE: [e.g.1.8.0_231]

**Comment by mrjesen** [comment]
已知晓，正在定位问题。

**Comment by mrjesen** [comment]
已解决，稍后上传新版本。

**Comment by LangYueMc** [comment]
新包没classes啊 23333，快重新打包

**Comment by LangYueMc** [comment]
V1.0.10没有class文件，快重新打包
