### ISSUE TITLE
[BUG] 加入ImBlocker后无法启动游戏

### ISSUE THREAD

**Issue by Cccc-owo** [mrjesen/ImBlockerFabric#13]
**Describe the bug**
加入ImBlocker后无法启动游戏

**Client Software**
PCLⅡ (MC: 1.16.4)

**mods**
如图
![image](https://user-images.githubusercontent.com/47687154/101176329-49b1c400-3681-11eb-828e-6b5408ea1bba.png)

**To Reproduce**
1. 在无本模组的情况下加入本模组
2. 启动游戏即崩溃

**Expected behavior**
正常启动

**Screenshots**

![image](https://user-images.githubusercontent.com/47687154/101176486-85e52480-3681-11eb-8d2e-4cf30615f6cd.png)

**Environment(please complete the following information):**
 - OS: [Windows 10 20H2]
 - JRE: [1.8.0_261]

**Additional context**
日志:
[latest.log](https://github.com/mrjesen/ImBlockerFabric/files/5643371/latest.log)

**Comment by mrjesen** [comment]
不好意思，release那里上传错文件了。
