### ISSUE TITLE
[BUG] ImBlocker 1.0.10 crash in MC1.16.4

### ISSUE THREAD

**Issue by YehowahLiu** [mrjesen/ImBlockerFabric#14]
**Describe the bug**
Game crash when using this mod in mc1.16.4.
I have tried to disable all other mods, still crash.
For details, check the link at last.

**Client Software**
MultiMC(MC: 1.16.4)

**mods**
 shows in the crash log at last.

**To Reproduce**
Just use this mod in MC version 1.16.4

**Expected behavior**
Game should be launched without error.

**Screenshots**
No need for screenshots.

**Environment(please complete the following information):**
 - OS: Windows10 20H2 (19042.662)
 - JRE: 1.8.0_251

**Additional context**
[crash log with other mods](https://paste.ee/p/KPB7n)
[crash log without other mods](https://paste.ee/p/IzRZ8)

**Comment by YehowahLiu** [comment]
BTW, I used the latest fabric loader, which is 1.10.8 now.

**Comment by YehowahLiu** [comment]
同 #13 , 打扰了，但希望还是能尽快修复一下

**Comment by mrjesen** [comment]
请查看1.0.10版本。

**Comment by YehowahLiu** [comment]
重新下载后可以正常使用了，所以是更新过一次文件然后没有换版本号？我看版本都是1.0.10以为就是最新的了...
