### ISSUE TITLE
关于物品栏关闭时的输入冲突问题·续(BUG)

### ISSUE THREAD

**Issue by Hambaka** [mrjesen/ImBlockerFabric#2]
**描述bug:**
1. 之前[#1](https://github.com/mrjesen/ImBlockerFabric/issues/1)提到的创造模式物品栏关闭时的输入冲突已确认完全修复。
2. 在生存模式中，开启了合成书功能的物品栏，之前[#1](https://github.com/mrjesen/ImBlockerFabric/issues/1)提到的核心问题已经修复。但是关闭物品栏时有一个非常小的问题。打开物品栏之后，必须鼠标随便点击一个位置以确认当前输入状态之后，才能直接按"E"关闭物品栏（只要不点那个合成配方搜索栏，点其它任何位置之后就可以直接按"E"关闭物品栏了）。如果打开物品栏后无任何后续操作直接按"E"，会跳出输入法。

**bug重现方式:**
大体流程同上。

**预期结果:**
生存模式按"E"打开开启了合成书功能的物品栏之后，可无需其他操作直接按"E"关闭，不会跳出输入法。

**截图:**
无

**运行环境:**
 - 操作系统: Windows 10 专业版 Version 1909
 - 输入法: 中文(简体，中国)，微软拼音；英语(美国)，美式键盘
 - Minecraft: 1.16.1
 - Fabric: 0.9.0+build.204
 - Mod版本: 1.0.4
 - 同时运行的其它Mod:  fabric-api-0.15.0+build.379-1.16.1, modmenu-1.14.5+build.30
 - 分支: master

**额外说明:**
1. 开启了合成书的物品栏只有上面描述的小问题，别的问题暂时没发现，输入模式和非输入模式之间的切换功能是正常的。
2. 本问题同样适用于工作台，熔炉，高炉以及烟熏炉这种也有合成书模式的功能方块（应该也只有这些方块带有合成书切换模式按钮）。这些方块的问题基本与第二条行为相同。

**Comment by mrjesen** [comment]
你提到第二点没有复现成功

**Comment by mrjesen** [comment]
我打开生存模式物品栏并点击合成书按钮，并没有出现你所说的情况

**Comment by mrjesen** [comment]
就在刚才我成功复现了，概率确实小。

**Comment by mrjesen** [comment]
我明白了，是我的习惯问题，我一般出现左上角输入法召唤出来之后，直接按shift，不过这个问题确实得修复一下。

**Comment by mrjesen** [comment]
不行，我本地测试成功了，但是我另一个整合包出错了，我重新弄一下吧。

**Comment by mrjesen** [comment]
暂时只修复了铁砧，合成书这个没搞定。

**Comment by mrjesen** [comment]
已修复，v1.0.6版本亲测可用。

**Comment by Hambaka** [comment]
1.0.6版本的合成书，其中四个状态目前修好了三个，就差最后一个不好用。

1.当前为普通模式，按"E"打开物品栏后可直接按"E"关闭。
2.当前为普通模式，按"E"打开物品栏，之后按合成书按钮切换到合成书模式，此时可直接按"E"关闭。
3.当前为合成书模式，按"E"打开物品栏后可直接按"E"关闭。
4.当前为合成书模式，按"E"打开物品栏，之后按合成书按钮切换到普通模式，此时可直接按"E"关闭。

目前版本前三个都是可以的，只有第四个的最后一步操作会跳出输入法。
