### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by plusls** [mrjesen/ImBlockerFabric#23]
Readme 更新

感觉目前 readme 的 curseforge 的数据有一些问题，可以参考 TIS carpet 的写法

![image](https://user-images.githubusercontent.com/23459592/111657968-e40bd100-8846-11eb-8331-259c3ce1df17.png)

https://github.com/TISUnion/Carpet-TIS-Addition/blob/master/README.md

**Comment by mrjesen** [comment]
最近很忙，没多少时间弄这个，我尽快release吧

**Comment by mrjesen** [comment]
看了一下，因为风格我不太喜欢，所以不会用这个badge。
