### ISSUE TITLE
关于物品栏关闭时的输入冲突问题·续2(BUG)

### ISSUE THREAD

**Issue by Hambaka** [mrjesen/ImBlockerFabric#3]
**描述bug:**
1. 属于之前[#1](https://github.com/mrjesen/ImBlockerFabric/issues/1)中额外说明部分产生的bug。而且此bug只出现在生存模式
2. 此时物品栏未开启合成书功能，打开和直接关闭都是可以的，但是如果打开物品栏后点击合成书，切换到合成书模式之后，行为同之前[#2](https://github.com/mrjesen/ImBlockerFabric/issues/2)的第二条，也就是需要点击任意位置确认当前输入状态之后才能按"E"直接关闭物品栏，否则跳出输入法。关闭并再次开启物品栏之后的行为依旧同[#2](https://github.com/mrjesen/ImBlockerFabric/issues/2)的第二条。
3. 如果是反过来操作，也就是物品栏开启了合成书功能的情况下，打开物品栏后，如果我点击合成书切换为无合成书功能的普通物品栏，其行为基本类似之前#1的额外说明部分，不管我点击哪里都是强制为输入状态，只能按"ESC"强制关闭。关闭并再次开启物品栏之后一切功能正常。不过如果此时继续点击合成书切换为合成书模式，就会陷入第2步的套娃……

**bug重现方式:**
大体流程同上。

**预期结果:**
切换物品栏模式之后可直接按"E"关闭物品栏。

**截图:**
无

**运行环境:**
 - 操作系统: Windows 10 专业版 Version 1909
 - 输入法: 中文(简体，中国)，微软拼音；英语(美国)，美式键盘
 - Minecraft: 1.16.1
 - Fabric: 0.9.0+build.204
 - Mod版本: 1.0.4
 - 同时运行的其它Mod:  fabric-api-0.15.0+build.379-1.16.1, modmenu-1.14.5+build.30
 - 分支: master

**额外说明:**
1. 本问题同样适用于工作台，熔炉，高炉以及烟熏炉这种也有合成书模式的功能方块（应该也只有这些方块带有合成书切换模式按钮）。这些方块的问题基本与第二条与第三条行为相同。

**Comment by mrjesen** [comment]
已读，#2 联系
