### ISSUE TITLE
关于铁砧界面交互时的输入冲突问题(BUG)

### ISSUE THREAD

**Issue by Hambaka** [mrjesen/ImBlockerFabric#4]
**描述bug:**
1. 本问题算是原版就存在的问题。
2. 右键打开铁砧后，不论我在做什么，都是处于输入文字模式，输入法持续跳出，导致无法按"E"关闭界面，只能"ESC"强制关闭。

**bug重现方式:**
大体流程同上。

**预期结果:**
行为与英文输入法一致，只有我将物品移动到铁砧的物品槽里，才会激活铁砧重命名的文本输入框，此时开启输入文字的模式。只要铁砧物品槽没有东西也就不会激活输入框，此时按"E"可直接关闭界面。

**截图:**
无

**运行环境:**
 - 操作系统: Windows 10 专业版 Version 1909
 - 输入法: 中文(简体，中国)，微软拼音；英语(美国)，美式键盘
 - Minecraft: 1.16.1
 - Fabric: 0.9.0+build.204
 - Mod版本: 1.0.4
 - 同时运行的其它Mod:  fabric-api-0.15.0+build.379-1.16.1, modmenu-1.14.5+build.30
 - 分支: master

**额外说明:**
无

**Comment by mrjesen** [comment]
修复完毕，但是会导致打开铁砧界面不添加物品无法编辑命名，应该是理想状态吧。

**Comment by Hambaka** [comment]
试了一下1.0.6版本，铁砧的行为并没有修好，不是很清楚是什么问题导致的
