### ISSUE TITLE
[BUG] 1.18告示牌在某些情况下无法激活输入法

### ISSUE THREAD

**Issue by mrjesen** [mrjesen/ImBlockerFabric#42]
**Describe the bug**
1.18告示牌在某些情况下无法激活输入法

**Client Software**
PCL (MC: 1.18.1)

**mods**
未知

**Environment (Please complete the following information):**
反馈了两种环境：
1. win11+微软拼音
2. win10+搜狗拼音

反馈原文：
1. ```我这里用的win10+搜狗输入法也出同样问题了，告示牌不能打字，卸载正常1.18```
2. ```大佬您好，我想反馈一个小问题，就是使用了该mod以后，在使用告示牌拼写中文的时候无法输入汉字，只能输入英文，mod版本imblockerfabric-1.0.17.jar游戏版本1.18.1，谢谢``` ```大佬好，我是Win11 微软中文输入法```

**Comment by plusls** [comment]
这个是新版 rei 带来的影响，不过也算是历史遗留问题（指自己某些地方修复的不彻底
