### ISSUE TITLE
关于"打开聊天栏"与"输入命令"的默认行为逻辑改进及可行性(建议·优先级低)

### ISSUE THREAD

**Issue by Hambaka** [mrjesen/ImBlockerFabric#5]
**与该建议相关的问题:**
1.这点建议主要跟玩家行为逻辑相关，跟游戏体验挂钩。而且我个人也不知道这点是否可行。
2.Minecraft有两种方式打开聊天栏，一个就是"打开聊天栏"，默认是"T"，另一个就是"输入命令"，默认是"/"
3.对于玩家而言，一般情况下，聊天时肯定是使用"打开聊天栏"，基本上对我们而言肯定是说中文，也就是CJK各自的输入法。而打命令肯定就是直接按"/"了，而且基本也是打英文，可能就命令参数里比如NBT标签会牵涉中文。
4.所以这个建议是，能否让玩家每次按下"打开聊天栏"的按键时输入法默认输入中文，而玩家每次按下“输入命令”的按键时输入法默认输入英文。当然，这里的默认只是指每次打开聊天栏的初始状态，玩家打字的时候还是可以根据情况自己按shift切换到另一个模式，毕竟聊天时可能也需要打英文，打命令时也需要打中文。（初步构思）
5.不过考虑到部分玩家会去外国服务器玩游戏，可能面临全程打英文聊天的情况，关于这一点下面我有提到自己的思考。

**可行的思路/方案:**
1.并不懂开发这一块儿，所以也没办法提供思路或者方案。
2.但是如果这个功能真的做出来，进一步细化的方案我是构思的。
3.构想中的这个详细功能，是有配置面板，可以通过游戏中命令打开，比如什么"/imblocker"打开配置面板，又或者可以通过ModMenu对Mod进行直接配置。
4.构想中的思路是配置面板有三个选项，分别管理"打开聊天栏"，"输入命令"以及"通用"选项，每个选项可以自己选择默认输入CJK或者默认输入英文。通用很好理解，就是除了"打开聊天栏"和"输入命令"之外的所有情况，比如写书，搜索，木牌，等等这些所有其余的情况。
5.当然这些都是纯构想，能否实现我都不清楚，而且这样做还得整一套UI，还挺麻烦。如果能实现我上面说的最基础的功能我认为就很不错了。

**其它思路/方案:**
无

**额外说明:**
1.通过这个issue把我的这个想法发出来，主要是想问问是否可行，如果可行的话那就最好了，而且优先级低，不用着急弄。
2.而且话说这issue关的好快，二和四的问题我试了一下还是有问题，但是issue已经关闭了，虽然我在后面回复了不过也不知道能否收到，也不好意思新发一次，就把这个建议的issue发出来了。如果那两个问题修好了我认为本Mod应该没有自身存在的硬伤了（至少截至目前我没发现别的问题），也就方便在玩家间大范围推荐和推广了。

**Comment by mrjesen** [comment]
你这个问题我说实话不打算修复，我个人认为没有几个人是通过/按键输入命令的，都是直接通过T（被我改成了回车）输入命令。
至于你说的之前的#2没修复，我这里测试是修复了的，关闭是因为我习惯在commit message里面写上具体是哪个issue，但是message里面有issue默认就是关联关闭对应的issue，这个没办法改变。
对于你当前这个issue，我不打算采纳，因为我个人认为没有人使用/输入命令，都是直接聊天时候输入命令。

**Comment by mrjesen** [comment]
我做这个mod的目的就是一切从简，能不按键就按键，终极目标就是在需要输入的地方打开输入法，不需要的地方关闭输入法。

**Comment by Hambaka** [comment]
那我明白了，可能还是习惯和认知上的问题。因为我就是那种按T聊天（我也改到回车了），按/直接打命令的人(因为这个按键直接开头补了/，对我来说很方便)，所以想问题可能也是从自己习惯出发的。还有，至于我认为还没修好的2和4，我现在不清楚到底是怎么回事，所以就等别人确认吧。

**Comment by mrjesen** [comment]
我这里测试了，是确认确认 #2 #4 已经修复了的
