### ISSUE TITLE
[BUG] 在REI安装的前提下，搜索物品不能输入中文

### ISSUE THREAD

**Issue by mrjesen** [mrjesen/ImBlockerFabric#52]
**Describe the bug**
在REI安装的前提下，搜索物品不能输入中文

**Client Software**
Maybe 1.18.2

**Screenshot**

![image](https://user-images.githubusercontent.com/29056691/175343235-002cad6a-a7bf-4c7f-850e-2711c44f6699.png)

**Comment by plusls** [comment]
奇怪 为啥我没碰上（周末再说.jpg

**Comment by mrjesen** [comment]
> 奇怪 为啥我没碰上（周末再说.jpg

 没准是他们自己的问题，实在不行就不修了 😎

**Comment by plusls** [comment]
测了一下1.1.9确实没问题呀，我119 的 mod 都是最新的，（118 没测

**Comment by mrjesen** [comment]
好叭，那就算了 不修了
