### ISSUE TITLE
[BUG] 1.0.19在Arch Linux上失效

### ISSUE THREAD

**Issue by MATRIX-feather** [mrjesen/ImBlockerFabric#53]
**Describe the bug**
升级到MC1.19之后似乎就失效了，几天前1.18还是正常的

**Client Software**
官启/Quilt (MC: 1.19)

**mods**
 - IMBlockerFabric 1.0.19
 - LazyDFU 0.1.2
 - Quilt Loader 0.17.0
 - Smooth Boot 1.19-1.7.1
 - ModMenu 4.0.0

**To Reproduce**
1. 启动游戏

**Expected behavior**
没弹其他游戏界面的时候会自动禁用输入法

**Environment (Please complete the following information):**
 - OS: Arch Linux
 - JRE: 17.0.3

**Additional context:**
- Fabric下也是一样的情况
- 桌面环境是GNOME 42.2
- 输入法是fcitx5-rime
- [latest.log](https://github.com/mrjesen/ImBlockerFabric/files/8980480/latest.log)

**Comment by plusls** [comment]
可能glfw更新了，然后寄了（有空看看，最近有亿点忙

**Comment by mrjesen** [comment]
java.lang.UnsatisfiedLinkError: libflite.so.1: 无法打开共享对象文件: 没有那个文件或目录

**Comment by mrjesen** [comment]
测试一下 只加载IMBlocker呢？其他的mod暂时禁用掉

**Comment by MATRIX-feather** [comment]
只加载IMBlocker的话问题还在；libflite是文本转语音的库，装不装都没啥影响_(:3」∠)_

[latest.log](https://github.com/mrjesen/ImBlockerFabric/files/8984186/latest.log)

**Comment by mrjesen** [comment]
> 只加载IMBlocker的话问题还在；libflite是文本转语音的库，装不装都没啥影响_(:3」∠)_
> 
> [latest.log](https://github.com/mrjesen/ImBlockerFabric/files/8984186/latest.log)

没有报错很烦

**Comment by plusls** [comment]
这个应该是native的问题，没办法，只能等我有空看看linux的咋改了
