### ISSUE TITLE
[BUG] Win11 1.16.5 jna getforgeground failed.

### ISSUE THREAD

**Issue by ShenxPresent** [mrjesen/ImBlockerFabric#54]
**Describe the bug**
1.16.5启动失败

**Client Software**
PCL2
**mods**
                modmenu: Mod Menu 1.16.23
		optifabric: OptiFabric 1.13.0
		phosphor: Phosphor 0.8.0
		physicsmod: Physics Mod 2.6.7
		replaymod: Replay Mod 1.16.4-2.6.5
		smoothboot: Smooth Boot 1.16.5-1.5.0
		voicechat: Simple Voice Chat 1.16.5-1.3.13
**To Reproduce**
启动后立即崩溃
**Expected behavior**
游戏能正常启动

**Environment (Please complete the following information):**
 - OS:win 11
 - JRE: 1.8.0_261

**Comment by ShenxPresent** [comment]
[crash-2022-06-30_03.56.52-client.txt](https://github.com/mrjesen/ImBlockerFabric/files/9014072/crash-2022-06-30_03.56.52-client.txt)

**Comment by mrjesen** [comment]
想修 但没有win11环境，怎么破

**Comment by mrjesen** [comment]
不修了
