### ISSUE TITLE
控制-按键绑定中添加开关输入法的按键绑定设置[增强] 

### ISSUE THREAD

**Issue by GodGun968** [mrjesen/ImBlockerFabric#57]
1.19.2
因为有的界面需要输入法但是输入法没有出来所以想要一个按键来控制,我看语言文件里有这个选项,但是进了游戏啥也没找到啊

**Comment by mrjesen** [comment]
😢是想做这个来着，后来添加完语言设置就。。。忘了
下个版本加一下按键控制吧

**Comment by GodGun968** [comment]
好叭 感谢
