### ISSUE TITLE
[BUG] 1.19.3进入世界时游戏崩溃

### ISSUE THREAD

**Issue by ItIsNotAPlayer** [mrjesen/ImBlockerFabric#58]
**Describe the bug**
游戏窗口可以打开，但是进入世界时游戏会崩溃

**Client Software**
PCL2 (MC: 1.19.3/Fabric: 0.14.11)

**mods**
 - IMBlockerFabric 1.0.19

**To Reproduce**
1. 打开游戏
2. 随便进入一个世界
3. 会在“进入世界中”界面卡住，可能还会未响应
4. 直接跳到“保存游戏中”，随后游戏崩溃

**Environment**
 - OS: Windows 10 22H2
 - JRE: 17.0.5

**Additional context**
[crash-2022-12-16_16.10.07-client.txt](https://github.com/mrjesen/ImBlockerFabric/files/10244018/crash-2022-12-16_16.10.07-client.txt)

**Comment by mrjesen** [comment]
收到，因为生病原因，近期修复。

**Comment by mrjesen** [comment]
@plusls 这兼容挺麻烦啊，mojang又把SignEditScreen的finnishEditing挪到AbstractSignEditScreen下面了。
