### ISSUE TITLE
MOD加载后报错崩溃

### ISSUE THREAD

**Issue by hds1160311048** [mrjesen/ImBlockerFabric#6]
Minecraft 1.15.2 ，已经安装Fabric API 0.6.2 build322 for1.15，启动后报错崩溃
[minecraft-exported-logs-2020-08-04T09-04-32.log](https://github.com/mrjesen/ImBlockerFabric/files/5020237/minecraft-exported-logs-2020-08-04T09-04-32.log)

**Comment by mrjesen** [comment]
已收到，在问题定位前，请使用v1.0.1版本，谢谢支持~

**Comment by mrjesen** [comment]
暂时先用1.0.2吧，这个月我好像没时间fix了。

**Comment by hds1160311048** [comment]
好的，谢谢
