### ISSUE TITLE
[FEATURE] 游戏内设置

### ISSUE THREAD

**Issue by l666685** [mrjesen/ImBlockerFabric#61]
**Type**
添加白名单设置功能(因为有些mod的页面一开始不支持)

**Description**
类似于Forge版，可以在游戏内更改配置，从而添加可以输入的mod页面

**Usage**
emm，可以联动模组菜单mod，在菜单内配置

**Additional context**
![屏幕截图 2023-01-06 120044](https://user-images.githubusercontent.com/105541501/210927516-a00a51dd-b7a1-4c39-83be-5138350432b2.png)

**Comment by l666685** [comment]
大佬还有多久开始搞袜QWQ

**Comment by mrjesen** [comment]
> 大佬还有多久开始搞袜QWQ

哈哈 会尽快的。

**Comment by mrjesen** [comment]
思来想去不做这个功能了，目前精力放到其他项目啦
