### ISSUE TITLE
[BUG] 在Manjaro上使用fcitx输入法时毫无效果

### ISSUE THREAD

**Issue by addpromax** [mrjesen/ImBlockerFabric#63]
**Describe the bug**
在Manjaro上使用fcitx输入法时毫无效果

**Client Software**
HMCL (MC: 1.19.3)

**mods**
 - imblockerfabric-1.0.20

**To Reproduce**
1. 安装imblockerfabric-1.0.20
2. 进入MC
3. 无效 按F6也不行

**Expected behavior**
应该可以正常使用

**Screenshots**
No

**Environment (Please complete the following information):**
 - OS: Linux 6.1.12-1-MANJARO x86_64
 - JRE: OpenJDK Runtime Environment Temurin-18.0.2.1+1 (build 18.0.2.1+1)

**Additional context**

**Comment by mrjesen** [comment]
Same as #53
