### ISSUE TITLE
[BUG] 1.19.4下与RoughlyEnoughItems(REI物品管理器)冲突

### ISSUE THREAD

**Issue by lolisaikou** [mrjesen/ImBlockerFabric#65]
**Describe the bug**
好像是mixin注入失败，说是找不到”setFocused“的目标

**Client Software**
HMCL (MC: 1.19.4)

**mods**
	- 在日志中提供

**To Reproduce**
1. 安装此mod后打开游戏

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/32028165/226184254-8bf88507-f07b-4cf8-9822-b252ba87519b.png)

**Environment (Please complete the following information):**
 - OS: Windows 11
 - JRE: 17.0.3, Microsoft

**Additional context**
[日志](https://gist.github.com/lolisaikou/eedc54f17fdf2fb0ab23b4dd07585d61)

**Comment by mrjesen** [comment]
@plusls 大佬修一下，我最近没时间哈哈😎

**Comment by pan90** [comment]
快修bug，没有它我活不了，呜呜呜~

**Comment by GodGun968** [comment]
呜呜呜 我也有这个问题找半天

**Comment by lolisaikou** [comment]
@pan90 @GodGun968 我自己编译了一份不注入REI的版本，当然这会导致搜索框无法输入中文，不过REI已经支持全拼搜索了所以问题不大，先拿去凑合用[imblockerfabric-1.0.20_pre4.zip](https://github.com/mrjesen/ImBlockerFabric/files/11128280/imblockerfabric-1.0.20_pre4.zip)

**Comment by GodGun968** [comment]
> @pan90 @GodGun968 我自己编译了一份不注入REI的版本，当然这会导致REI的搜索框无法输入中文，不过REI已经支持全拼搜索了所以问题不大，先拿去凑合用[imblockerfabric-1.0.20_pre4.zip](https://github.com/mrjesen/ImBlockerFabric/files/11128280/imblockerfabric-1.0.20_pre4.zip)

你真的我哭死谢谢

**Comment by mrjesen** [comment]
感谢大家理解，如果p佬不修的话，我这边事情忙完预计4.7开始修复。

**Comment by Hendrix-Shen** [comment]
尝试在 #66 中修复此问题，仍需要更多测试，可以试试 [这个](https://github.com/mrjesen/ImBlockerFabric/suites/11972923748/artifacts/628215823) 版本。

**Comment by mrjesen** [comment]
已修复。 请从最新Release下载。

**Comment by GodGun968** [comment]
好耶awa
