### ISSUE TITLE
[BUG] 1.0.20_pre5在1.19.4上无法输入中文

### ISSUE THREAD

**Issue by lsp7878578** [mrjesen/ImBlockerFabric#69]
**描述错误**
imblockerfabric-1.0.20_pre5在1.19.4fabric上用中文输入会导致中英切换反复横跳

**客户端软件**
PCL2 和HMCL（MC： 1.19.4）

**模组**
 - [FPS减速器]FpsReducer2-fabric-1.19.4-2.3
 - [Reese的钠视频界面] reeses_sodium_options-1.5.0+mc1.19.4-build
 - [干净利落] cleancut-1.19.4-5.3-fabric
 - [更好的树叶渲染优化] CullLessLeaves-1.1.0
 - [流畅加载] smoothboot-fabric-1.19.4-1.7.0
 - [钠 · 扩展] sodium-extra-0.4.19+mc1.19.3-build.101
 - [3d皮肤层]3dskinlayers-fabric-1.5.3-mc1.19.4
 - AdaptiveTooltips-1.2.1-fabric-1.19.4
 - AdvancedChatCore-1.19.4-1.5.10
 - AdvancedChatHUD-1.19.4-1.3.8
 - appleskin-fabric-mc1.19.4-2.4.3
 - [更好的钠视频界面]bsvsb-3.0.3
 - c2me-fabric-mc1.19.4-0.2.0+alpha.10.51
 - camerautils-1.19.4-1.0.4
 - DarkKore-0.3.5-1.19.4
 - DetailArmorBar-2.6.3+1.19.4-fabric
 - fabric-api-0.80.0+1.19.4
 - fabricskyboxes-0.6.5+mc1.19.4
 - ferritecore-5.2.0-fabric
 - fsb-interop-1.2.0+mc1.19.4-build.31{fsb是fabricskyboxes简写)
 - I18nUpdateMod-3.4.2-all
 - imblockerfabric-1.0.20_pre5
 - ImmediatelyFast-1.1.12+1.19.4
 - indium-1.0.17+mc1.19.4
 - iris-mc1.19.4-1.6.2
 - KronHUD-1.19.4-2.2.5
 - lambdynamiclights-2.3.0+1.19.4
 - lithium-fabric-mc1.19.4-0.11.1
 - magiclib-0.7.293+17aa28c-stable
 - malilib-fabric-1.19.4-0.15.4
 - modmenu-6.2.2
 - OfflineSkins-1.19.4-v1a-fabric
 - PlayerHealthIndicators-1.1.0-1.19.3
 - sodium-fabric-mc1.19.4-0.4.11+build.26
 - starlight-1.1.1+fabric.ae22326
 - tweakeroo-fabric-1.19.4-0.16.0
 - viafabricplus-2.6.8
 - yet-another-config-lib-fabric-2.5.1+1.19.4

**复制**
重现行为的步骤：
1. 启动mc
2. 进入游戏
3. "T"键打开聊天框
4. 快捷键"ctrl"+空格切换中文
5. 输入(无法输入,中英切换标志狂跳

**预期行为**
希望能修复这一bug，重振雄风（不是）

**环境（请填写以下信息）:**
 - 操作系统：win 10专业版 22h2
 - JRE： zulu19.32.13-ca-jdk19.0.2-win_x64

**其他上下文**
在此处添加有关该问题的任何其他上下文。
[minecraft-exported-logs-2023-05-07T23-36-01.log](https://github.com/mrjesen/ImBlockerFabric/files/11415462/minecraft-exported-logs-2023-05-07T23-36-01.log)
[I18nUpdateMod.log](https://github.com/mrjesen/ImBlockerFabric/files/11415464/I18nUpdateMod.log)
[latest.log](https://github.com/mrjesen/ImBlockerFabric/files/11415465/latest.log)

**Comment by mrjesen** [comment]
方便测试一下只安装imblockerfabric-1.0.20_pre5和fabric-api-0.80.0+1.19.4吗

**Comment by mrjesen** [comment]
在最新的正式版也没复现你的问题。

**Comment by lsp7878578** [comment]
> 方方便测试一下只安装imblockerfabric-1.0.20_pre5和fabric-api-0.80.0+1.19.4这两个mod吗 我这里测试了一下1.19.4 Pre 3版本，没有复现你说的问题题。

只安装imblockerfabric-1.0.20_pre5和fabric-api-0.80.0+1.19.4这两个mod没有什么问题，能正常输入中文，
[minecraft-exported-logs-2023-05-08T13-49-07.log](https://github.com/mrjesen/ImBlockerFabric/files/11418208/minecraft-exported-logs-2023-05-08T13-49-07.log)
但是再继续安装AdvancedChatCore-1.19.4-1.5.10、AdvancedChatHUD-1.19.4-1.3.8、malilib-fabric-1.19.4-0.15.4就会出现上述问题
[minecraft-exported-logs-2023-05-08T13-51-24.log](https://github.com/mrjesen/ImBlockerFabric/files/11418228/minecraft-exported-logs-2023-05-08T13-51-24.log)

**Comment by mrjesen** [comment]
> > 方方便测试一下只安装imblockerfabric-1.0.20_pre5和fabric-api-0.80.0+1.19.4这两个mod吗 我这里测试了一下1.19.4 Pre 3版本，没有复现你说的问题题。
> 
> 只安装imblockerfabric-1.0.20_pre5和fabric-api-0.80.0+1.19.4这两个mod没有什么问题，能正常输入中文， [minecraft-exported-logs-2023-05-08T13-49-07.log](https://github.com/mrjesen/ImBlockerFabric/files/11418208/minecraft-exported-logs-2023-05-08T13-49-07.log) 但是再继续安装AdvancedChatCore-1.19.4-1.5.10、AdvancedChatHUD-1.19.4-1.3.8、malilib-fabric-1.19.4-0.15.4就会出现上述问题 [minecraft-exported-logs-2023-05-08T13-51-24.log](https://github.com/mrjesen/ImBlockerFabric/files/11418228/minecraft-exported-logs-2023-05-08T13-51-24.log)

ok了解了，会尽快调整

**Comment by lsp7878578** [comment]
> > 方方便测试一下只安装imblockerfabric-1.0.20_pre5和fabric-api-0.80.0+1.19.4这两个mod吗 我这里测试了一下1.19.4 Pre 3版本，没有复现你说的问题题。
> 
> 只安装imblockerfabric-1.0.20_pre5和fabric-api-0.80.0+1.19.4这两个mod没有什么问题，能正常输入中文， [minecraft-exported-logs-2023-05-08T13-49-07.log](https://github.com/mrjesen/ImBlockerFabric/files/11418208/minecraft-exported-logs-2023-05-08T13-49-07.log) 但是是继续安装AdvancedChatCore-1.19.4-1.5.10、AdvancedChatHUD-1.19.4-1.3.8、malilib-fabric-1.19.4-0.15.4就会出现上面描述的问题 [minecraft-exported-logs-2023-05-08T13 -51-24.log](https://github.com/mrjesen/ImBlockerFabric/files/11418228/minecraft-exported-logs-2023-05-08T13-51-24.log)

只安装malilib-fabric-1.19.4-0.15.4、imblockerfabric-1.0.20_pre5和fabric-api-0.80.0+1.19.4也没有任何问题，继续安装AdvancedChatCore-1.19.4-1.5.10（AdvancedChatHUD-1.19.4-1.3.8的前置mod）就会导致中英切换反复横跳   

[minecraft-exported-logs-2023-05-08T14-07-45.log](https://github.com/mrjesen/ImBlockerFabric/files/11418310/minecraft-exported-logs-2023-05-08T14-07-45.log)

![d6e29448731701f858a4ccc8d33c08a8~1](https://user-images.githubusercontent.com/110713423/236748000-1811a581-13bf-4a5f-a443-e9162143abae.gif)

**Comment by mrjesen** [comment]
尝试使用1.0.21 并手动开关输入法。
