### ISSUE TITLE
建议直接标记为客户端mod

### ISSUE THREAD

**Issue by Sanluli36li** [mrjesen/ImBlockerFabric#7]
ImBlockerFabric/src/main/resources/fabric.mod.json第19行
`"environment": "client",`
![image](https://user-images.githubusercontent.com/5201743/92219346-05b9f200-eecd-11ea-9521-37c5f3470cb7.png)

简单修改了一下jar 没问题，懒得弄pull request了

**Comment by mrjesen** [comment]
好的

**Comment by mrjesen** [comment]
修复了
