### ISSUE TITLE
[BUG] ` Invalid descriptor on #imblocker:imblocker.mixins.json:ftbquests.MixinQuestsTextBox`

### ISSUE THREAD

**Issue by SettingDust** [mrjesen/ImBlockerFabric#71]
imblockerfabric-1.0.21
ftb-quests-fabric-1902.4.16-build.235
1.19.2 quilt

**Describe the bug**
`org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on #imblocker:imblocker.mixins.json:ftbquests.MixinQuestsTextBox from mod imblocker->@Inject::presetFocused(ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V! Expected (ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V [INJECT Applicator Phase -> #imblocker:imblocker.mixins.json:ftbquests.MixinQuestsTextBox from mod imblocker -> Apply Injections ->  -> Inject -> #imblocker:imblocker.mixins.json:ftbquests.MixinQuestsTextBox from mod imblocker->@Inject::presetFocused(ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V]
`

**Comment by mrjesen** [comment]
[ImblockerFabric.zip](https://github.com/mrjesen/ImBlockerFabric/files/11641761/ImblockerFabric.2.zip)
Try this version plz.
