### ISSUE TITLE
[BUG] Crash when loading worlds

### ISSUE THREAD

**Issue by FlameFire26** [mrjesen/ImBlockerFabric#73]
**Describe the bug**
Loading single-player world or join multi-player world, crash during the loading screen.

**Client Software**
PCL2 (MC: 1.20)

**Environment **
 - OS: Windows 11 22H2
 - JRE: 17.0.3.1

[crash-2023-06-13_15.48.56-client.txt](https://github.com/mrjesen/ImBlockerFabric/files/11732153/crash-2023-06-13_15.48.56-client.txt)

**Comment by mrjesen** [comment]
rogar,i'll fix it today.

**Comment by mrjesen** [comment]
fixed
