### ISSUE TITLE
[BUG] 在1.20.0使用时发生崩溃

### ISSUE THREAD

**Issue by north82** [mrjesen/ImBlockerFabric#74]
**Describe the bug**
使用此mod时产生崩溃

**Client Software**
Multimc (MC: 1.20.0)

**mods**
 - IMBlockerFabric v1.0.21
 - Fabric-api-0.83.0
 
**To Reproduce**
1. 启动游戏
2. 进入单人存档或服务器

**Expected behavior**
正常进入世界

**Environment (Please complete the following information):**
 - OS: [win 10 专业版 22h2]
 - JRE: [17.0.1]

**Additional context**
[crash-2023-06-13_19.37.45-client.txt](https://github.com/mrjesen/ImBlockerFabric/files/11734332/crash-2023-06-13_19.37.45-client.txt)

**Comment by qiuzilu** [comment]
目前还不支持1.20，请耐心等待模组更新喵~

**Comment by KaguraXun** [comment]
curseforge上显示已经支持1.20.。。

**Comment by qiuzilu** [comment]
IDK，他俩版本号一样，一个显示到1.19.4，一个显示到1.20.1

**Comment by mrjesen** [comment]
收到，今天修复。

**Comment by qiuzilu** [comment]
快点更，离开它我已经不会玩游戏啦QAQ

**Comment by mrjesen** [comment]
> 快点更，离开它我已经不会玩游戏啦QAQ

已经在coding了

**Comment by qiuzilu** [comment]
![X8J(LBW8BGMSUTQBY(917%Q](https://github.com/mrjesen/ImBlockerFabric/assets/64822124/b4d7fd36-6343-427d-97d1-4397cb74b1ff)

**Comment by mrjesen** [comment]
已修复。
