### ISSUE TITLE
[BUG] 强制英文输入

### ISSUE THREAD

**Issue by qiuzilu** [mrjesen/ImBlockerFabric#75]
PCL2 
Minecraft 1.20 Fabric，Fabric API 0.83.0
ImBlockerFabric v1.0.22
Windows 10 22H2
JRE 17.07 64bit
使用微软输入法
貌似给强制英文输入法了，怎么按都切换不了中文输入

**Comment by mrjesen** [comment]
默认就是禁用输入法。 目前是想要在哪里输入？

**Comment by qiuzilu** [comment]
啊，我想在聊天栏输入中文
我记得之前是自动切换的
按下F6之后，非输入栏状态时输入法能蹦出来，一旦切换输入栏，又强制英文了

**Comment by mrjesen** [comment]
好家伙，又来个bug 我再修一下

**Comment by qiuzilu** [comment]
辛苦啦
![3}@`AP 11V880F JJ6QO`Y5](https://github.com/mrjesen/ImBlockerFabric/assets/64822124/6a0a8a75-fc1e-422c-8d45-93b8f7123cf6)

**Comment by mrjesen** [comment]
试一下新版本，不能用的话 直接 reopen 这个 issue

**Comment by qiuzilu** [comment]
经测试，该bug已被修复，模组功能正常，谢谢——

> 试一下新版本，不能用的话 直接 reopen 这个 issue
