### ISSUE TITLE
[BUG] Didn't see any effect. Mod is correctly installed and enabled.

### ISSUE THREAD

**Issue by surfishs** [mrjesen/ImBlockerFabric#76]
![image](https://github.com/mrjesen/ImBlockerFabric/assets/96485650/9b487eec-3c35-4803-9ba4-3f6d4ee7f3cd)
![image](https://github.com/mrjesen/ImBlockerFabric/assets/96485650/0a6883c8-b8c8-4fa1-a7db-84c8b436f585)

**Comment by surfishs** [comment]
我没按照要求的格式填写，很抱歉，因为我觉得我描述的已经足够了，并且mcmod上似乎也出现了很多关于最新版本的无法使用反馈。

**Comment by mrjesen** [comment]
I think you should describe your MC version at least. And I want to know something else,such as OS version,mod version.

**Comment by surfishs** [comment]
Minecraft1.20.1,windows10,fabric-loader-0.14.21,v1.0.23,Only this mod
[latest.log](https://github.com/mrjesen/ImBlockerFabric/files/11760231/latest.log)

**Comment by surfishs** [comment]
> I think you should describe your MC version at least. And I want to know something else,such as OS version,mod version. If your mc version is 1.20.1, upload your log file please.

PLZ,fix it.
