### ISSUE TITLE
[BUG] 打开背包界面、存档选择界面无法输入中文

### ISSUE THREAD

**Issue by JesKi13567** [mrjesen/ImBlockerFabric#77]
**Describe the bug**
创造模式搜索特定物品、生存模式搜索配方、单人存档搜索存档名都无法输入中文。

**Client Software**
PCL2 (MC: 1.20.1)

**mods**
 - IMBlockerFabric v1.0.23
 - Fabric 0.14.21
 - Fabric API 0.83.1

**To Reproduce**
1. 随便进个单人档或多人游戏（不进游戏无法复现）
2. 在背包发现无法输入中文
3. 退出当前档后，无法在单人游戏存档、多人游戏服务器名进行编辑

**Expected behavior**
首先背包界面肯定得能正常输入中文，其次游戏存档搜索和服务器名修改也得能输入中文

**Environment (Please complete the following information):**
 - OS: Windows 10 22H2 家庭中文版
 - JRE: java 17.0.5 LTS

**Comment by mrjesen** [comment]
日志please

**Comment by JesKi13567** [comment]
[2023-06-20-3.log](https://github.com/mrjesen/ImBlockerFabric/files/11814485/2023-06-20-3.log)
