### ISSUE TITLE
不能在其他mod提供的输入框中输入中文

### ISSUE THREAD

**Issue by Logic530** [mrjesen/ImBlockerFabric#9]
在 REI VoxelMap 等mod提供的输入框中无法输入中文

非常感谢提供这个方便的mod，希望能尽快解决这个问题

**Comment by mrjesen** [comment]
收到，我会尽快修复

**Comment by mrjesen** [comment]
综合考虑了一下，与其适配每一个mod还不如保持目前状态不动。

**Comment by Logic530** [comment]
等…作者大大等一下，我觉得这应该是有能自动适配所有mod的方法吧，毕竟jec就支持很多mod的搜索框……难道jec也是一个一个适配的吗

**Comment by plusls** [comment]
rei 自己重写了一个文本框，得单独对 rei mixin
